[이은지] 1장: 리액트 개발을 위해 꼭 알아야 할 자바스크립트
muhandojeon/Modern-React-Deep-Dive pull request #9
Opened 2023-12-05 12:42 UTC by eunddodi

2023-12-05 13:46 UTC, hyesungoh requested changes
으앗 .DS_Store 없애주시고 
깃이그노어 추가해주실 수 있나요 ㅋㅋㅋㅋ

2023-12-05 13:55 UTC, eunddodi commented
@

> 으앗 .DS_Store 없애주시고
> 깃이그노어 추가해주실 수 있나요 ㅋㅋㅋㅋ

오엠지~ 알겠슴다

2023-12-10 10:38 UTC, hyesungoh approved these changes
제가 해뒀음요 👍

2023-12-14 15:06 UTC, hyesungoh commented
이거 깃이그노어 땜시 머지할게용

2023-12-14 15:06 UTC, merged